export const PolicyEventTypes = {
  SUBMISSION_CREATED: 'SubmissionCreated',
  SUBMISSION_DATA_UPDATED: 'SubmissionDataUpdated',
  RISK_ADDED: 'RiskAdded',
  RISK_REMOVED: 'RiskRemoved',
  COVERAGE_SELECTED: 'CoverageSelected',
  COVERAGE_REMOVED: 'CoverageRemoved',
  UNDERWRITING_REVIEW_STARTED: 'UnderwritingReviewStarted',
  UNDERWRITING_APPROVED: 'UnderwritingApproved',
  UNDERWRITING_DECLINED: 'UnderwritingDeclined',
  UNDERWRITING_REFERRED: 'UnderwritingReferred',
  RATING_REQUESTED: 'RatingRequested',
  RATING_COMPLETED: 'RatingCompleted',
  QUOTE_GENERATED: 'QuoteGenerated',
  POLICY_BOUND: 'PolicyBound',
  POLICY_ISSUED: 'PolicyIssued',
  POLICY_IN_FORCE: 'PolicyInForce',
  ENDORSEMENT_REQUESTED: 'EndorsementRequested',
  ENDORSEMENT_APPLIED: 'EndorsementApplied',
  RENEWAL_INITIATED: 'RenewalInitiated',
  RENEWAL_COMPLETED: 'RenewalCompleted',
  CANCELLATION_REQUESTED: 'CancellationRequested',
  CANCELLATION_APPLIED: 'CancellationApplied',
  REINSTATEMENT_REQUESTED: 'ReinstatementRequested',
  REINSTATEMENT_APPLIED: 'ReinstatementApplied',
} as const;
